feat(cli): add 'bundle validate' command (#27)
* ci: add 'bundle validate' in lint job

* ci: fix regression due to a stricter date validation

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -75,9 +75,13 @@ jobs:
             if ! go run ./ bundle generate \
               --config .tpm-roots.yaml \
               --output test-bundle.pem \
-              --date 0000-00-00 \
+              --date 1970-01-01 \
               --commit 0000000000000000000000000000000000000000; then
               echo "bundle generate command failed ⛔"
+              exit 1
+            fi
+            if ! go run ./ bundle validate test-bundle.pem; then
+              echo "bundle validate command failed ⛔"
               exit 1
             fi
             echo "no linting issues found 💫"
