ci: add 'bundle validate' in lint job

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -80,4 +80,8 @@ jobs:
               echo "bundle generate command failed ⛔"
               exit 1
             fi
+            if ! go run ./ bundle validate test-bundle.pem; then
+              echo "bundle validate command failed ⛔"
+              exit 1
+            fi
             echo "no linting issues found 💫"
